# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

# 注册测试
#POST  http://127.0.0.1:9000/system/signup
#Content-Type: application/json
#
## roleId 暂时设计为 0, 1, 2，分别代表admin，MVO，BVO
#{
#  "username": "LSKReno2",
#  "password": "lskreno",
#  "roleId": "2"
#}


# 登录测试
#POST  http://127.0.0.1:9000/system/login
#Content-Type: application/json
#
#{
#  "username": "LSKReno",
#  "password": "lskreno"
#}


#POST  http://127.0.0.1:9000/business/manManufacturer/list
#Content-Type: application/json
#Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ7XCJ1c2VySWRcIjoxLFwidXNlcm5hbWVcIjpcIkxTS1Jlbm9cIn0iLCJpYXQiOjE1OTQwODk2MDAsImV4cCI6MTU5NDA5MzIwMH0.J7qEUE1nZE5LgrgoyYmttvQKvqbx4RdFqjkZ5rYQamWc1es1sn8TCSf115g4cpF3EWXRZWCoPtNCBIZLovSU3A
#
#{
#
#}








