# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

# 菜单测试
POST  http://127.0.0.1:9000/system/menu
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ7XCJyb2xlSWRcIjpcIjFcIixcInVzZXJJZFwiOjEsXCJ1c2VybmFtZVwiOlwiTFNLUmVub1wifSIsImlhdCI6MTU5NDExMzU1NywiZXhwIjoxNTk0MTE3MTU3fQ.Pz1xsGoj9AxJ6KmqyCQCig-T-I4TcwZtgJVbVMEtOdGUlF9j_5FXzrZtSL27ELCm1AhqTUeKSy57MwIM6E5dvw

{
  "userId": "2"
}

###



//{
//  "content": [
//    {
//      "menuId": 1,
//      "menuTitle": "AdminMenuTitle",
//      "menuName": "AdminMenu",
//      "menuUrl": "/admin",
//      "parentId": "1000",
//      "menuOrder": "1000",
//      "menuIcon": "setting",
//      "menuType": null,
//      "menuRedirect": null,
//      "menuMetadata": null,
//      "deleted": null
//    },
//    {
//      "menuId": 2,
//      "menuTitle": "AdminSubMenu1Title",
//      "menuName": "AdminSubMenu1",
//      "menuUrl": "/admin/sub1",
//      "parentId": "1000",
//      "menuOrder": "1001",
//      "menuIcon": "setting",
//      "menuType": null,
//      "menuRedirect": null,
//      "menuMetadata": null,
//      "deleted": null
//    }
//  ]
//}
