# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST  http://127.0.0.1:9001/system/mvoproduct/update
Content-Type: application/json

{
  "proId": "8",
  "title": "woeifore",
  "skuCd": "skrrrrr",
  "upc": "uuppcc",
  "ean": "eannea",
  "model": "modellingggg",
  "warrantyDay": "20200703",
  "descrition": "dd",
  "price": "9.0",
  "length": "7.7",
  "weight": "4.3",
  "height": "5.6",
  "width": "2.2",
  "manId": "9",
  "lastUpdateBy": "usssss",
  "uri": "yoerihoqierwurg3"
}

###
