# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST  http://127.0.0.1:9001/system/mvo/product/insert
Content-Type: application/json

{
  "title": "orggg",
  "skuCd": "sekura4",
  "upc": "unpvccc",
  "ean": "e112345",
  "model": "232r0x",
  "warrantyDay": "20200705",
  "descrition": "hbbbbuul",
  "price": "99",
  "length": "7.3",
  "weight": "45",
  "height": "5.00",
  "width": "23.0",
  "manId": "1",
  "createdBy": "zeraaa",
  "stsCd": "A"
}

###,
#  "uri": "www9913"





