# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST  http://127.0.0.1:9000/system/mvo/product/insert
Content-Type: application/json

{
  "title": "table",
  "skuCd": "biofds",
  "upc": "93822",
  "ean": "fsds345",
  "model": "2sdsx",
  "warrantyDay": "20200715",
  "descrition": "nononoononoononono",
  "retailPrice": "220.3",
  "length": "7.44",
  "weight": "5.55",
  "height": "8",
  "width": "20",
  "userId": "3",
  "createdBy": "Sum",
  "stsCd": "A"
}

###,
#  "uri": "www9913"





