# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST  http://127.0.0.1:9000/system/mvo/product/insert
Content-Type: application/json

{
  "title": "iphone 11",
  "skuCd": "sskkuu",
  "upc": "upc95032",
  "ean": "ean23233",
  "model": "rx0000x",
  "warrantyDay": "20220715",
  "descrition": "very very expensive",
  "retailPrice": "9999999",
  "length": "7.44",
  "weight": "5.55",
  "height": "8.88",
  "width": "3.14",
  "userId": "3",
  "createdBy": "LSKReno3",
  "stsCd": "A"
}

###,
#  "uri": "www9913"





