# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://127.0.0.1:9001/system/bvo/borrow
Content-Type: application/json

{
  "userId": "4",
  "proId": "1",
  "strId": "1",
  "ofpId": "5",
  "dropshipPrice": "12",
  "dropshipStatus": "A",
  "createdBy": "ccc",
  "shelfStock": "99",
  "preferDate": "2020-07-19 00:00:00",
  "witId": "2"
}

###